# -*- coding: utf-8 -*-
"""freshman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJ8XJcNk5yshF4Xmsb9bgKWy5v89UZLn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 물 계산 함수
def trap_water_np(height_list):
    height = np.array(height_list)
    n = len(height)

    left_max = np.maximum.accumulate(height)
    right_max = np.maximum.accumulate(height[::-1])[::-1]
    water_heights = np.minimum(left_max, right_max) - height
    water_heights = np.clip(water_heights, 0, None)

    total_water = water_heights.sum()
    return int(total_water), water_heights

# 시각화 및 출력 함수
def plot_trap_water_np(height_list, example_number=None):
    total, trapped = trap_water_np(height_list)

    title = f"Example {example_number}" if example_number else "Trapping Rain Water"
    print("="*60)
    print(f"{title}")
    print(f"Input height: {height_list}")
    print(f"Total trapped water: {total}")
    print(f"Water trapped at each index: {trapped.tolist()}")
    print("="*60 + "\n")

    df = pd.DataFrame({
        'Index': np.arange(len(height_list)),
        'Ground': height_list,
        'Water': trapped
    })

    plt.figure(figsize=(10, 4))
    plt.bar(df['Index'], df['Ground'], color='black', label='Ground')
    plt.bar(df['Index'], df['Water'], bottom=df['Ground'], color='blue', alpha=0.5, label='Water')

    plt.title(f"{title}\nTrapped Water = {total}", fontsize=14)
    plt.xlabel("Index", fontsize=12)
    plt.ylabel("Height", fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

# ✅ 예시 1
example1 = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]
plot_trap_water_np(example1, example_number=1)

# ✅ 예시 2
example2 = [4, 2, 0, 3, 2, 5, 2, 1, 4, 0, 3, 1]
plot_trap_water_np(example2, example_number=2)

# ✅ 예시 3
example3 = [2, 0, 2, 7, 4, 1, 3, 5, 2, 2, 0, 5]
plot_trap_water_np(example3, example_number=3)